import assert from 'node:assert/strict';
import {HeartController} from '../frontend/heart-controller.mjs';
const calls=[],reports=[];
let model={_modelHomeDir:'/ds-whale-girl/',_expressions:{getValue:()=>({})},setExpression:e=>calls.push(e)};
const adapter={getModel:()=>model};
const controller=new HeartController(async (s,status)=>reports.push(status));
const state={ready:true,enabled:true,command_id:'a',valid_expression:true,expression:'问号'};
await controller.update(state,adapter);
await controller.update(state,adapter);
assert.deepEqual(calls,['问号']);
assert.equal(controller.owns(),true);
await controller.update({...state,command_id:'b',expression:'星星眼'},adapter);
assert.deepEqual(calls,['问号','星星眼']);
model={...model};await controller.update({...state,command_id:'b',expression:'星星眼'},adapter);
assert.equal(calls.length,3,'模型重新加载后重放当前状态');
await controller.update({...state,command_id:'c',valid_expression:false},adapter);
assert.equal(reports.at(-1),'failed');
await controller.update(state,null);
assert.equal(reports.at(-1),'unavailable');
await controller.update({ready:false},adapter);
assert.equal(controller.owns(),false);
console.log('PASS: persistent state, no repeated reaction, base restoration, reload and failure receipts');
// Different Open-LLM-VTuber model, including an expression at numeric index 0.
const otherCalls=[];
const otherModel={_modelHomeDir:'/mao_pro/',_expressions:{getValue:name=>name==='idle' ? 0 : null},setExpression:name=>otherCalls.push(name)};
const otherAdapter={getModel:()=>otherModel,getExpressionName:index=>index===0?'idle':undefined};
await controller.update({...state,command_id:'alternate-model',expression:0},otherAdapter);
assert.deepEqual(otherCalls,['idle']);
assert.equal(reports.at(-1),'applied');
await controller.update({...state,command_id:'missing',expression:99},otherAdapter);
assert.equal(reports.at(-1),'unavailable');
console.log('PASS: non-fish model, numeric index zero, missing expression');
let attempts=0;
const retryStatuses=[], retryCalls=[];
const retryModel={...model,setExpression:e=>retryCalls.push(e)};
const retryController=new HeartController(async (s,status)=>{
  retryStatuses.push(status);
  if (++attempts===1) throw Error('temporary network failure');
});
await assert.rejects(retryController.update(state,{getModel:()=>retryModel}));
await retryController.update(state,{getModel:()=>retryModel});
assert.deepEqual(retryCalls,['问号'],'回执重试不能重放表情');
assert.deepEqual(retryStatuses,['applied','applied'],'回执网络失败不误记为动作失败');
console.log('PASS: receipt retries do not replay or misreport expression');
